### ISSUE TITLE
Mage > Information Update Request

### ISSUE THREAD

**Issue by ChaosWebDev** [colinchilds/MerenthaCollective#15]
"Ok, I'm casting a lot of spells and running out of magic a lot now, is there a better way to get it back besides sleeping?"
> From levels 1 to 3 you can drink from the Cabeiri fountain. After that you'll probably want to start buying mana orbs in Whitestorm for 35 platinum each. The shop is to the west, in the magic district. These orbs heal your magic constantly and much faster than sleep. You can have up to 3 draining at a time, with 3 in reserve. If you buy more than 6, they will start to meld together randomly. There are some other ways to recover magic, as well as other orb shops, but you'll have to find those for yourself.

There are some changes to this --

From levels 1 to 3 you can drink from the Cabeiri fountain. After that you'll probably want to start buying mana orbs in Whitestorm for 35 platinum each. The shop is to the west, in the magic district. These orbs heal your magic constantly and much faster than sleep. You can have up to 3 draining at a time, with **additional orbs** in reserve. You can change the drain speed of the orbs to *drain quickly*, *drain normally*, or *drain slowly* ~~If you buy more than 6, they will start to meld together randomly.~~ There are some other ways to recover magic, as well as other orb shops, but you'll have to find those for yourself.

**Comment by ChaosWebDev** [comment]
I submitted a pull request for this.

**Comment by colinchilds** [comment]
We don’t have a deploy process in place to get this out. I’ll look at setting up a GitHub action for it.

**Comment by michaelprograms** [comment]
> We don’t have a deploy process in place to get this out. I’ll look at setting up a GitHub action for it.

I just deployed it manually, but yeah this repo could use some dependency/action updates/love. ;)

**Comment by colinchilds** [comment]
Haha that’s why I open sourced it ;)

**Comment by colinchilds** [comment]
Done. It should be deploying automatically on pushes to main now. I'll go ahead and start poking around the dependencies and such
